sudo: false
language: python
python:
  - "2.7"
  - "3.5"
cache: apt
addons:
   apt:
      packages:
      - libatlas-dev
      - libatlas-base-dev
      - liblapack-dev
      - gfortran

before_install:
  - git submodule update --init --recursive
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy pytest pytest-cov mock
  - pip install pep8 python-coveralls
  - pip install -r requirements.txt
script:
  - make test
after_success:
  - coveralls
